apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "historical.fullname" . }}-jmx-exporter
  labels:
    app: {{ template "historical.name" . }}
    chart: {{ template "historical.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yml: |-
    hostPort: 127.0.0.1:{{ .Values.global.jmx_exporter.JMXPORT }}
    rules:
    - pattern: ".*"
    ssl: false
    startDelaySeconds: {{ .Values.global.jmx_exporter.startDelaySeconds }}
