{
 "title": "Druid",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "druid_env",
    "label": "Environment",
    "query": "label_values(segment_size, druid_env)"
   }
  ]
 },
 "panels": [
  { "title": "Coordinator stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Segment size total by node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(segment_size{druid_env=\"$druid_env\", druid_role=\"coordinator\", druid_datasource=~\".+\"}) by (druid_datasource)",
     "legendFormat": "{{druid_datasource}}"
    }
   ]
  },
  {
   "title": "Load queue size, bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "segment_loadQueue_size{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{druid_neighbour_hostPort}} (historical node)"
    }
   ]
  },
  {
   "title": "Load queue failed, count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "segment_loadQueue_failed{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{druid_neighbour_hostPort}} (historical node)"
    }
   ]
  },
  {
   "title": "Load queue, count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "segment_loadQueue_count{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{druid_neighbour_hostPort}} (historical node)"
    }
   ]
  },
  {
   "title": "Drop queue, count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "segment_dropQueue_count{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{druid_neighbour_hostPort}} (historical node)"
    }
   ]
  },
  {
   "title": "Coordinator overall stats, count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "segment_overShadowed_count{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "segment_moved_count{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "segment_dropped_count{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "segment_assigned_count{druid_env=\"$druid_env\", druid_role=\"coordinator\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  { "title": "Broker stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Query cache deltas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({druid_env=\"$druid_env\", druid_role=\"broker\", __name__=~\"query_cache_delta.*\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Query cache totals",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({druid_env=\"$druid_env\", druid_role=\"broker\", __name__=~\"query_cache_total.*\"}) by (__name__)",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "CPU time spent per datasource query (groupBy)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(query_cpu_time_groupBy_sum{druid_env=\"$druid_env\", druid_role=\"broker\"} / query_cpu_time_groupBy_count{druid_env=\"$druid_env\", druid_role=\"broker\"}) by (druid_datasource)",
     "legendFormat": "{{druid_datasource}}"
    }
   ]
  },
  {
   "title": "Time spent for groupBy by datasource",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(query_time_groupBy_sum{druid_env=\"$druid_env\", druid_role=\"broker\"} / query_time_groupBy_count{druid_env=\"$druid_env\", druid_role=\"broker\"}) by (druid_datasource)",
     "legendFormat": "{{druid_datasource}}"
    }
   ]
  },
  {
   "title": "Time spent for groupBy by instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(query_time_groupBy_sum{druid_env=\"$druid_env\", druid_role=\"broker\"} / query_time_groupBy_count{druid_env=\"$druid_env\", druid_role=\"broker\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent for query by node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "query_node_time_sum{druid_env=\"$druid_env\", druid_role=\"broker\"} / query_node_time_count{druid_env=\"$druid_env\", druid_role=\"broker\"}",
     "legendFormat": "{{druid_neighbour_hostPort}} (historical node)"
    }
   ]
  },
  {
   "title": "Time to first byte in Queries by node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "query_node_ttfb_sum{druid_env=\"$druid_env\", druid_role=\"broker\"} / query_node_ttfb_count{druid_env=\"$druid_env\", druid_role=\"broker\"}",
     "legendFormat": "{{druid_neighbour_hostPort}} (historical node)"
    }
   ]
  },
  { "title": "Historical stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU time spent in groupBy queries per datasource by datasource",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(query_cpu_time_groupBy_sum{druid_env=\"$druid_env\", druid_role=\"historical\"} / query_cpu_time_groupBy_count{druid_env=\"$druid_env\", druid_role=\"historical\"}) by (druid_datasource)",
     "legendFormat": "{{druid_datasource}}"
    }
   ]
  },
  {
   "title": "CPU time spent in groupBy queries per datasource by node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(query_cpu_time_groupBy_sum{druid_env=\"$druid_env\", druid_role=\"historical\"} / query_cpu_time_groupBy_count{druid_env=\"$druid_env\", druid_role=\"historical\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent to process a query",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "query_time_groupBy_sum{druid_env=\"$druid_env\", druid_role=\"historical\"} / query_time_groupBy_count{druid_env=\"$druid_env\", druid_role=\"historical\"}"
    }
   ]
  },
  {
   "title": "Time spent to reach segment or cache",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "query_segmentAndCache_time_sum{druid_env=\"$druid_env\", druid_role=\"historical\"} / query_segmentAndCache_time_count{druid_env=\"$druid_env\", druid_role=\"historical\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent to query segment",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "query_segment_time_sum{druid_env=\"$druid_env\", druid_role=\"historical\"} / query_segment_time_count{druid_env=\"$druid_env\", druid_role=\"historical\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent waiting for segment scan",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "query_wait_time_sum{druid_env=\"$druid_env\", druid_role=\"historical\"} / query_wait_time_count{druid_env=\"$druid_env\", druid_role=\"historical\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Overlord stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Size of new segments created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(segment_added_bytes{druid_env=\"$druid_env\", druid_role=\"overlord\"})  by (druid_datasource)",
     "legendFormat": "{{druid_datasource}}"
    }
   ]
  },
  {
   "title": "Time  taken to run task",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "task_run_time_sum{druid_env=\"$druid_env\", druid_role=\"overlord\"} / task_run_time_count{druid_env=\"$druid_env\", druid_role=\"overlord\"}",
     "legendFormat": "{{druid_tasktype}} for {{druid_datasource}}"
    }
   ]
  }
 ]
}