---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
{{ include "indexer.labels" . | indent 4 }}
data:
{{ (tpl (.Files.Glob "files/*").AsConfig .) | indent 2 }}
