apiVersion: v1
kind: Service
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
{{ include "indexer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9102
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 5556
      targetPort: jmx
      protocol: TCP
      name: jmx
  selector:
    app.kubernetes.io/name: {{ include "indexer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
