apiVersion: v1
kind: Service
metadata:
  name: {{ include "indexer.fullname" . }}-headless
  labels:
{{ include "indexer.labels" . | indent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "indexer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
