apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
{{ include "indexer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "indexer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "indexer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config-common: {{ .Values.global.druid | toYaml | sha256sum }}
        checksum/config: {{ .Values.druid | toYaml | sha256sum }}
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-common
          configMap:
            name: {{ .Release.Name }}-common
        - name: {{ .Release.Name }}-jmx-exporter
          configMap:
            name: {{ .Release.Name }}-jmx-exporter
        - name: {{ template "indexer.fullname" . }}
          configMap:
            name: {{ template "indexer.fullname" . }}
{{ include "monitoring.volumes" . | indent 8 }}
      containers:
        - name: jmx-exporter
          image: "{{ .Values.global.jmx_exporter.image.repository }}:{{ .Values.global.jmx_exporter.image.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ .Release.Name }}-jmx-exporter
              mountPath: /opt/jmx_exporter/config.yml
              subPath: config.yml
        - name: druid # {{ .Chart.Name }} - universal container name for druid is better
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DRUID_ROLE
              value: {{ .Values.DRUID_ROLE | quote }}
            - name: JAVA_OPTS
              value: {{ .Values.global.indexer.druid.JAVA_OPTS | quote }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8091 
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/druid/conf/_common/
              name: {{ .Release.Name }}-common
            - mountPath: /opt/druid/conf/indexer/
              name: {{ template "indexer.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{ include "monitoring.containers" . | indent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
