---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-common
  labels:
    app: {{ template "druid.name" . }}
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (tpl (.Files.Glob "files/druid/configs/_common/*").AsConfig .) | indent 2 }}
