{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app: {{ template "druid.name" . }}
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.monitoring.serviceMonitor.additionalLabels }}
{{ toYaml .Values.monitoring.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.scrapeInterval }}
      {{- if .Values.monitoring.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
    - port: jmx
      interval: {{ .Values.monitoring.serviceMonitor.scrapeInterval }}
      {{- if .Values.monitoring.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
  {{- if .Values.monitoring.serviceMonitor.namespaceSelector }}
  namespaceSelector:
{{ toYaml .Values.monitoring.serviceMonitor.namespaceSelector | indent 4 -}}
  {{ else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
{{- end }}
