apiVersion: v1
kind: Service
metadata:
  name: {{ template "broker.fullname" . }}-headless
  labels:
    app: {{ template "broker.name" . }}
    chart: {{ template "broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "broker.name" . }}
    release: {{ .Release.Name }}
