apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "broker.fullname" . }}
  labels:
    app: {{ template "broker.name" . }}
    chart: {{ template "broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "broker.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "broker.fullname" . }}-headless
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "broker.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}
      annotations:
        checksum/config-common: {{ .Values.global.druid | toYaml | sha256sum }}
        checksum/config: {{ .Values.druid | toYaml | sha256sum }}
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-common
          configMap:
            name: {{ .Release.Name }}-common
        - name: {{ template "broker.fullname" . }}
          configMap:
            name: {{ template "broker.fullname" . }}
        - name: {{ .Release.Name }}-jmx-exporter
          configMap:
            name: {{ .Release.Name }}-jmx-exporter
{{ include "monitoring.volumes" . | indent 8 }}
      containers:
        - name: jmx-exporter
          image: "{{ .Values.global.jmx_exporter.image.repository }}:{{ .Values.global.jmx_exporter.image.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ .Release.Name }}-jmx-exporter
              mountPath: /opt/jmx_exporter/config.yml
              subPath: config.yml
        - name: druid # {{ .Chart.Name }} - universal container name for druid is better
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DRUID_ROLE
              value: {{ template "broker.name" . }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.druid.JAVA_OPTS | quote }}
              #            - name: MY_POD_IP
              #              valueFrom:
              #                fieldRef:
              #                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{ .Values.druid.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "wget -qO - http://localhost:{{.Values.druid.port}}/druid/broker/v1/loadstatus | grep -q '{\"inventoryInitialized\":true}'"
          readinessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "wget -qO - http://localhost:{{.Values.druid.port}}/druid/broker/v1/loadstatus | grep -q '{\"inventoryInitialized\":true}'"
          volumeMounts:
            - mountPath: /opt/druid/conf/_common/
              name: {{ .Release.Name }}-common
            - mountPath: /opt/druid/conf/broker/
              name: {{ template "broker.fullname" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{ include "monitoring.containers" . | indent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
